# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageSearch-macOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 6.0'
  pod 'RxSwift', '6.0.0'

  # Pods for ImageSearch-macOS

end
